// Generated by delombok at Mon Mar 30 15:24:38 IST 2026
package com.collabrium.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

public class AuthRequest {
    @Email(message = "Must be a valid email address")
    @NotBlank(message = "Email is required")
    private String email;
    @NotBlank(message = "Password is required")
    private String password;

    public static class AuthRequestBuilder {

        private String email;

        private String password;

        AuthRequestBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public AuthRequest.AuthRequestBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public AuthRequest.AuthRequestBuilder password(final String password) {
            this.password = password;
            return this;
        }

        public AuthRequest build() {
            return new AuthRequest(this.email, this.password);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "AuthRequest.AuthRequestBuilder(email=" + this.email + ", password=" + this.password + ")";
        }
    }

    public static AuthRequest.AuthRequestBuilder builder() {
        return new AuthRequest.AuthRequestBuilder();
    }

    public String getEmail() {
        return this.email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setEmail(final String email) {
        this.email = email;
    }

    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AuthRequest)) return false;
        final AuthRequest other = (AuthRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AuthRequest;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "AuthRequest(email=" + this.getEmail() + ", password=" + this.getPassword() + ")";
    }

    public AuthRequest() {
    }

    public AuthRequest(final String email, final String password) {
        this.email = email;
        this.password = password;
    }
}
