// Generated by delombok at Mon Mar 30 15:24:38 IST 2026
package com.collabrium.dto;

import jakarta.validation.constraints.NotBlank;
import java.time.LocalDateTime;

public class DocumentDto {
    private Long id;
    private Long projectId;
    @NotBlank(message = "File name is required")
    private String fileName;
    @NotBlank(message = "File URL is required")
    private String fileUrl;
    private String version;
    private String tag;
    private String fileSize;
    private String projectTitle;
    private UserDto uploadedBy;
    private LocalDateTime uploadedAt;

    public static class DocumentDtoBuilder {

        private Long id;

        private Long projectId;

        private String fileName;

        private String fileUrl;

        private String version;

        private UserDto uploadedBy;

        private LocalDateTime uploadedAt;

        DocumentDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public DocumentDto.DocumentDtoBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DocumentDto.DocumentDtoBuilder projectId(final Long projectId) {
            this.projectId = projectId;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DocumentDto.DocumentDtoBuilder fileName(final String fileName) {
            this.fileName = fileName;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DocumentDto.DocumentDtoBuilder fileUrl(final String fileUrl) {
            this.fileUrl = fileUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DocumentDto.DocumentDtoBuilder version(final String version) {
            this.version = version;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DocumentDto.DocumentDtoBuilder uploadedBy(final UserDto uploadedBy) {
            this.uploadedBy = uploadedBy;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public DocumentDto.DocumentDtoBuilder uploadedAt(final LocalDateTime uploadedAt) {
            this.uploadedAt = uploadedAt;
            return this;
        }

        public DocumentDto build() {
            return new DocumentDto(this.id, this.projectId, this.fileName, this.fileUrl, this.version, this.uploadedBy, this.uploadedAt);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "DocumentDto.DocumentDtoBuilder(id=" + this.id + ", projectId=" + this.projectId + ", fileName=" + this.fileName + ", fileUrl=" + this.fileUrl + ", version=" + this.version + ", uploadedBy=" + this.uploadedBy + ", uploadedAt=" + this.uploadedAt + ")";
        }
    }

    public static DocumentDto.DocumentDtoBuilder builder() {
        return new DocumentDto.DocumentDtoBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public Long getProjectId() {
        return this.projectId;
    }

    public String getFileName() {
        return this.fileName;
    }

    public String getFileUrl() {
        return this.fileUrl;
    }

    public String getVersion() {
        return this.version;
    }

    public String getTag() { return tag; }
    public void setTag(String tag) { this.tag = tag; }

    public String getFileSize() { return fileSize; }
    public void setFileSize(String fileSize) { this.fileSize = fileSize; }

    public String getProjectTitle() { return projectTitle; }
    public void setProjectTitle(String projectTitle) { this.projectTitle = projectTitle; }

    public UserDto getUploadedBy() {
        return this.uploadedBy;
    }

    public LocalDateTime getUploadedAt() {
        return this.uploadedAt;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setProjectId(final Long projectId) {
        this.projectId = projectId;
    }

    public void setFileName(final String fileName) {
        this.fileName = fileName;
    }

    public void setFileUrl(final String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public void setVersion(final String version) {
        this.version = version;
    }

    public void setUploadedBy(final UserDto uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    public void setUploadedAt(final LocalDateTime uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DocumentDto)) return false;
        final DocumentDto other = (DocumentDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$projectId = this.getProjectId();
        final java.lang.Object other$projectId = other.getProjectId();
        if (this$projectId == null ? other$projectId != null : !this$projectId.equals(other$projectId)) return false;
        final java.lang.Object this$fileName = this.getFileName();
        final java.lang.Object other$fileName = other.getFileName();
        if (this$fileName == null ? other$fileName != null : !this$fileName.equals(other$fileName)) return false;
        final java.lang.Object this$fileUrl = this.getFileUrl();
        final java.lang.Object other$fileUrl = other.getFileUrl();
        if (this$fileUrl == null ? other$fileUrl != null : !this$fileUrl.equals(other$fileUrl)) return false;
        final java.lang.Object this$version = this.getVersion();
        final java.lang.Object other$version = other.getVersion();
        if (this$version == null ? other$version != null : !this$version.equals(other$version)) return false;
        final java.lang.Object this$uploadedBy = this.getUploadedBy();
        final java.lang.Object other$uploadedBy = other.getUploadedBy();
        if (this$uploadedBy == null ? other$uploadedBy != null : !this$uploadedBy.equals(other$uploadedBy)) return false;
        final java.lang.Object this$uploadedAt = this.getUploadedAt();
        final java.lang.Object other$uploadedAt = other.getUploadedAt();
        if (this$uploadedAt == null ? other$uploadedAt != null : !this$uploadedAt.equals(other$uploadedAt)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DocumentDto;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $projectId = this.getProjectId();
        result = result * PRIME + ($projectId == null ? 43 : $projectId.hashCode());
        final java.lang.Object $fileName = this.getFileName();
        result = result * PRIME + ($fileName == null ? 43 : $fileName.hashCode());
        final java.lang.Object $fileUrl = this.getFileUrl();
        result = result * PRIME + ($fileUrl == null ? 43 : $fileUrl.hashCode());
        final java.lang.Object $version = this.getVersion();
        result = result * PRIME + ($version == null ? 43 : $version.hashCode());
        final java.lang.Object $uploadedBy = this.getUploadedBy();
        result = result * PRIME + ($uploadedBy == null ? 43 : $uploadedBy.hashCode());
        final java.lang.Object $uploadedAt = this.getUploadedAt();
        result = result * PRIME + ($uploadedAt == null ? 43 : $uploadedAt.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "DocumentDto(id=" + this.getId() + ", projectId=" + this.getProjectId() + ", fileName=" + this.getFileName() + ", fileUrl=" + this.getFileUrl() + ", version=" + this.getVersion() + ", uploadedBy=" + this.getUploadedBy() + ", uploadedAt=" + this.getUploadedAt() + ")";
    }

    public DocumentDto() {
    }

    public DocumentDto(final Long id, final Long projectId, final String fileName, final String fileUrl, final String version, final UserDto uploadedBy, final LocalDateTime uploadedAt) {
        this.id = id;
        this.projectId = projectId;
        this.fileName = fileName;
        this.fileUrl = fileUrl;
        this.version = version;
        this.uploadedBy = uploadedBy;
        this.uploadedAt = uploadedAt;
    }
}
