// Generated by delombok at Mon Mar 30 15:24:38 IST 2026
package com.collabrium.dto;

import java.util.List;
import java.util.Map;

public class ErrorResponse {
    private boolean success;
    private String message;
    private List<Map<String, String>> errors;

    public static ErrorResponse of(String message) {
        return new ErrorResponse(false, message, null);
    }

    public static ErrorResponse of(String message, List<Map<String, String>> errors) {
        return new ErrorResponse(false, message, errors);
    }

    public static class ErrorResponseBuilder {

        private boolean success;

        private String message;

        private List<Map<String, String>> errors;

        ErrorResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public ErrorResponse.ErrorResponseBuilder success(final boolean success) {
            this.success = success;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ErrorResponse.ErrorResponseBuilder message(final String message) {
            this.message = message;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ErrorResponse.ErrorResponseBuilder errors(final List<Map<String, String>> errors) {
            this.errors = errors;
            return this;
        }

        public ErrorResponse build() {
            return new ErrorResponse(this.success, this.message, this.errors);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "ErrorResponse.ErrorResponseBuilder(success=" + this.success + ", message=" + this.message + ", errors=" + this.errors + ")";
        }
    }

    public static ErrorResponse.ErrorResponseBuilder builder() {
        return new ErrorResponse.ErrorResponseBuilder();
    }

    public boolean isSuccess() {
        return this.success;
    }

    public String getMessage() {
        return this.message;
    }

    public List<Map<String, String>> getErrors() {
        return this.errors;
    }

    public void setSuccess(final boolean success) {
        this.success = success;
    }

    public void setMessage(final String message) {
        this.message = message;
    }

    public void setErrors(final List<Map<String, String>> errors) {
        this.errors = errors;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ErrorResponse)) return false;
        final ErrorResponse other = (ErrorResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isSuccess() != other.isSuccess()) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$errors = this.getErrors();
        final java.lang.Object other$errors = other.getErrors();
        if (this$errors == null ? other$errors != null : !this$errors.equals(other$errors)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ErrorResponse;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isSuccess() ? 79 : 97);
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        final java.lang.Object $errors = this.getErrors();
        result = result * PRIME + ($errors == null ? 43 : $errors.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "ErrorResponse(success=" + this.isSuccess() + ", message=" + this.getMessage() + ", errors=" + this.getErrors() + ")";
    }

    public ErrorResponse() {
    }

    public ErrorResponse(final boolean success, final String message, final List<Map<String, String>> errors) {
        this.success = success;
        this.message = message;
        this.errors = errors;
    }
}
