// Generated by delombok at Mon Mar 30 15:24:38 IST 2026
package com.collabrium.dto;

import com.collabrium.model.MilestoneStatus;
import jakarta.validation.constraints.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class MilestoneDto {
    private Long id;
    private Long projectId;
    private String projectTitle;
    @NotBlank(message = "Milestone title is required")
    private String title;
    private LocalDate dueDate;
    private MilestoneStatus status;
    @Min(value = 0, message = "Progress must be at least 0")
    @Max(value = 100, message = "Progress cannot exceed 100")
    private Integer progressPercentage;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public static class MilestoneDtoBuilder {

        private Long id;

        private Long projectId;

        private String title;

        private LocalDate dueDate;

        private MilestoneStatus status;

        private Integer progressPercentage;

        private LocalDateTime createdAt;

        private LocalDateTime updatedAt;

        MilestoneDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public MilestoneDto.MilestoneDtoBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MilestoneDto.MilestoneDtoBuilder projectId(final Long projectId) {
            this.projectId = projectId;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MilestoneDto.MilestoneDtoBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MilestoneDto.MilestoneDtoBuilder dueDate(final LocalDate dueDate) {
            this.dueDate = dueDate;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MilestoneDto.MilestoneDtoBuilder status(final MilestoneStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MilestoneDto.MilestoneDtoBuilder progressPercentage(final Integer progressPercentage) {
            this.progressPercentage = progressPercentage;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MilestoneDto.MilestoneDtoBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public MilestoneDto.MilestoneDtoBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public MilestoneDto build() {
            return new MilestoneDto(this.id, this.projectId, this.title, this.dueDate, this.status, this.progressPercentage, this.createdAt, this.updatedAt);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "MilestoneDto.MilestoneDtoBuilder(id=" + this.id + ", projectId=" + this.projectId + ", title=" + this.title + ", dueDate=" + this.dueDate + ", status=" + this.status + ", progressPercentage=" + this.progressPercentage + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    public static MilestoneDto.MilestoneDtoBuilder builder() {
        return new MilestoneDto.MilestoneDtoBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public Long getProjectId() {
        return this.projectId;
    }

    public String getProjectTitle() { return projectTitle; }
    public void setProjectTitle(String projectTitle) { this.projectTitle = projectTitle; }

    public String getTitle() {
        return this.title;
    }

    public LocalDate getDueDate() {
        return this.dueDate;
    }

    public MilestoneStatus getStatus() {
        return this.status;
    }

    public Integer getProgressPercentage() {
        return this.progressPercentage;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setProjectId(final Long projectId) {
        this.projectId = projectId;
    }

    public void setTitle(final String title) {
        this.title = title;
    }

    public void setDueDate(final LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public void setStatus(final MilestoneStatus status) {
        this.status = status;
    }

    public void setProgressPercentage(final Integer progressPercentage) {
        this.progressPercentage = progressPercentage;
    }

    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MilestoneDto)) return false;
        final MilestoneDto other = (MilestoneDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$projectId = this.getProjectId();
        final java.lang.Object other$projectId = other.getProjectId();
        if (this$projectId == null ? other$projectId != null : !this$projectId.equals(other$projectId)) return false;
        final java.lang.Object this$progressPercentage = this.getProgressPercentage();
        final java.lang.Object other$progressPercentage = other.getProgressPercentage();
        if (this$progressPercentage == null ? other$progressPercentage != null : !this$progressPercentage.equals(other$progressPercentage)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$dueDate = this.getDueDate();
        final java.lang.Object other$dueDate = other.getDueDate();
        if (this$dueDate == null ? other$dueDate != null : !this$dueDate.equals(other$dueDate)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MilestoneDto;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $projectId = this.getProjectId();
        result = result * PRIME + ($projectId == null ? 43 : $projectId.hashCode());
        final java.lang.Object $progressPercentage = this.getProgressPercentage();
        result = result * PRIME + ($progressPercentage == null ? 43 : $progressPercentage.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $dueDate = this.getDueDate();
        result = result * PRIME + ($dueDate == null ? 43 : $dueDate.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "MilestoneDto(id=" + this.getId() + ", projectId=" + this.getProjectId() + ", title=" + this.getTitle() + ", dueDate=" + this.getDueDate() + ", status=" + this.getStatus() + ", progressPercentage=" + this.getProgressPercentage() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    public MilestoneDto() {
    }

    public MilestoneDto(final Long id, final Long projectId, final String title, final LocalDate dueDate, final MilestoneStatus status, final Integer progressPercentage, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.projectId = projectId;
        this.title = title;
        this.dueDate = dueDate;
        this.status = status;
        this.progressPercentage = progressPercentage;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
