// Generated by delombok at Mon Mar 30 15:24:38 IST 2026
package com.collabrium.dto;

import com.collabrium.model.ProjectStatus;
import jakarta.validation.constraints.NotBlank;
import java.time.LocalDateTime;
import java.util.List;

public class ProjectDto {
    private Long id;
    @NotBlank(message = "Project title is required")
    private String title;
    @NotBlank(message = "Project description is required")
    private String description;
    private ProjectStatus status;
    private UserDto createdBy;
    private List<Long> memberIds;
    private List<MilestoneDto> milestones;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public static class ProjectDtoBuilder {

        private Long id;

        private String title;

        private String description;

        private ProjectStatus status;

        private UserDto createdBy;

        private List<Long> memberIds;

        private LocalDateTime createdAt;

        private LocalDateTime updatedAt;

        ProjectDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public ProjectDto.ProjectDtoBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ProjectDto.ProjectDtoBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ProjectDto.ProjectDtoBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ProjectDto.ProjectDtoBuilder status(final ProjectStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ProjectDto.ProjectDtoBuilder createdBy(final UserDto createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ProjectDto.ProjectDtoBuilder memberIds(final List<Long> memberIds) {
            this.memberIds = memberIds;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ProjectDto.ProjectDtoBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ProjectDto.ProjectDtoBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public ProjectDto build() {
            return new ProjectDto(this.id, this.title, this.description, this.status, this.createdBy, this.memberIds, this.createdAt, this.updatedAt);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "ProjectDto.ProjectDtoBuilder(id=" + this.id + ", title=" + this.title + ", description=" + this.description + ", status=" + this.status + ", createdBy=" + this.createdBy + ", memberIds=" + this.memberIds + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    public static ProjectDto.ProjectDtoBuilder builder() {
        return new ProjectDto.ProjectDtoBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public String getTitle() {
        return this.title;
    }

    public String getDescription() {
        return this.description;
    }

    public ProjectStatus getStatus() {
        return this.status;
    }

    public UserDto getCreatedBy() {
        return this.createdBy;
    }

    public List<Long> getMemberIds() {
        return this.memberIds;
    }

    public List<MilestoneDto> getMilestones() { return milestones; }
    public void setMilestones(List<MilestoneDto> milestones) { this.milestones = milestones; }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setTitle(final String title) {
        this.title = title;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setStatus(final ProjectStatus status) {
        this.status = status;
    }

    public void setCreatedBy(final UserDto createdBy) {
        this.createdBy = createdBy;
    }

    public void setMemberIds(final List<Long> memberIds) {
        this.memberIds = memberIds;
    }

    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ProjectDto)) return false;
        final ProjectDto other = (ProjectDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdBy = this.getCreatedBy();
        final java.lang.Object other$createdBy = other.getCreatedBy();
        if (this$createdBy == null ? other$createdBy != null : !this$createdBy.equals(other$createdBy)) return false;
        final java.lang.Object this$memberIds = this.getMemberIds();
        final java.lang.Object other$memberIds = other.getMemberIds();
        if (this$memberIds == null ? other$memberIds != null : !this$memberIds.equals(other$memberIds)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ProjectDto;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdBy = this.getCreatedBy();
        result = result * PRIME + ($createdBy == null ? 43 : $createdBy.hashCode());
        final java.lang.Object $memberIds = this.getMemberIds();
        result = result * PRIME + ($memberIds == null ? 43 : $memberIds.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "ProjectDto(id=" + this.getId() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", status=" + this.getStatus() + ", createdBy=" + this.getCreatedBy() + ", memberIds=" + this.getMemberIds() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    public ProjectDto() {
    }

    public ProjectDto(final Long id, final String title, final String description, final ProjectStatus status, final UserDto createdBy, final List<Long> memberIds, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.status = status;
        this.createdBy = createdBy;
        this.memberIds = memberIds;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
