// Generated by delombok at Mon Mar 30 15:24:38 IST 2026
package com.collabrium.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "documents")
public class Document {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "uploaded_by", nullable = false)
    private User uploadedBy;
    @Column(nullable = false)
    private String fileName;
    @Column(nullable = false, columnDefinition = "TEXT")
    private String fileUrl;
    @Column(nullable = false)
    private String version;
    @Column
    private String tag;
    @Column
    private String fileSize;
    @Column(nullable = false, updatable = false)
    private LocalDateTime uploadedAt;

    @PrePersist
    protected void onCreate() {
        uploadedAt = LocalDateTime.now();
        if (version == null) version = "1.0.0";
    }

    public static class DocumentBuilder {

        private Long id;

        private Project project;

        private User uploadedBy;

        private String fileName;

        private String fileUrl;

        private String version;

        private LocalDateTime uploadedAt;

        DocumentBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public Document.DocumentBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Document.DocumentBuilder project(final Project project) {
            this.project = project;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Document.DocumentBuilder uploadedBy(final User uploadedBy) {
            this.uploadedBy = uploadedBy;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Document.DocumentBuilder fileName(final String fileName) {
            this.fileName = fileName;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Document.DocumentBuilder fileUrl(final String fileUrl) {
            this.fileUrl = fileUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Document.DocumentBuilder version(final String version) {
            this.version = version;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Document.DocumentBuilder uploadedAt(final LocalDateTime uploadedAt) {
            this.uploadedAt = uploadedAt;
            return this;
        }

        public Document build() {
            return new Document(this.id, this.project, this.uploadedBy, this.fileName, this.fileUrl, this.version, this.uploadedAt);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "Document.DocumentBuilder(id=" + this.id + ", project=" + this.project + ", uploadedBy=" + this.uploadedBy + ", fileName=" + this.fileName + ", fileUrl=" + this.fileUrl + ", version=" + this.version + ", uploadedAt=" + this.uploadedAt + ")";
        }
    }

    public static Document.DocumentBuilder builder() {
        return new Document.DocumentBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public Project getProject() {
        return this.project;
    }

    public User getUploadedBy() {
        return this.uploadedBy;
    }

    public String getVersion() {
        return this.version;
    }

    public String getFileName() {
        return this.fileName;
    }

    public String getFileUrl() {
        return this.fileUrl;
    }

    public String getTag() {
        return this.tag;
    }

    public String getFileSize() {
        return this.fileSize;
    }

    public LocalDateTime getUploadedAt() {
        return this.uploadedAt;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setProject(final Project project) {
        this.project = project;
    }

    public void setUploadedBy(final User uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    public void setFileName(final String fileName) {
        this.fileName = fileName;
    }

    public void setFileUrl(final String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public void setVersion(final String version) {
        this.version = version;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public void setUploadedAt(final LocalDateTime uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Document)) return false;
        final Document other = (Document) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$project = this.getProject();
        final java.lang.Object other$project = other.getProject();
        if (this$project == null ? other$project != null : !this$project.equals(other$project)) return false;
        final java.lang.Object this$uploadedBy = this.getUploadedBy();
        final java.lang.Object other$uploadedBy = other.getUploadedBy();
        if (this$uploadedBy == null ? other$uploadedBy != null : !this$uploadedBy.equals(other$uploadedBy)) return false;
        final java.lang.Object this$fileName = this.getFileName();
        final java.lang.Object other$fileName = other.getFileName();
        if (this$fileName == null ? other$fileName != null : !this$fileName.equals(other$fileName)) return false;
        final java.lang.Object this$fileUrl = this.getFileUrl();
        final java.lang.Object other$fileUrl = other.getFileUrl();
        if (this$fileUrl == null ? other$fileUrl != null : !this$fileUrl.equals(other$fileUrl)) return false;
        final java.lang.Object this$version = this.getVersion();
        final java.lang.Object other$version = other.getVersion();
        if (this$version == null ? other$version != null : !this$version.equals(other$version)) return false;
        final java.lang.Object this$uploadedAt = this.getUploadedAt();
        final java.lang.Object other$uploadedAt = other.getUploadedAt();
        if (this$uploadedAt == null ? other$uploadedAt != null : !this$uploadedAt.equals(other$uploadedAt)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Document;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $project = this.getProject();
        result = result * PRIME + ($project == null ? 43 : $project.hashCode());
        final java.lang.Object $uploadedBy = this.getUploadedBy();
        result = result * PRIME + ($uploadedBy == null ? 43 : $uploadedBy.hashCode());
        final java.lang.Object $fileName = this.getFileName();
        result = result * PRIME + ($fileName == null ? 43 : $fileName.hashCode());
        final java.lang.Object $fileUrl = this.getFileUrl();
        result = result * PRIME + ($fileUrl == null ? 43 : $fileUrl.hashCode());
        final java.lang.Object $version = this.getVersion();
        result = result * PRIME + ($version == null ? 43 : $version.hashCode());
        final java.lang.Object $uploadedAt = this.getUploadedAt();
        result = result * PRIME + ($uploadedAt == null ? 43 : $uploadedAt.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "Document(id=" + this.getId() + ", project=" + this.getProject() + ", uploadedBy=" + this.getUploadedBy() + ", fileName=" + this.getFileName() + ", fileUrl=" + this.getFileUrl() + ", version=" + this.getVersion() + ", uploadedAt=" + this.getUploadedAt() + ")";
    }

    public Document() {
    }

    public Document(final Long id, final Project project, final User uploadedBy, final String fileName, final String fileUrl, final String version, final LocalDateTime uploadedAt) {
        this.id = id;
        this.project = project;
        this.uploadedBy = uploadedBy;
        this.fileName = fileName;
        this.fileUrl = fileUrl;
        this.version = version;
        this.uploadedAt = uploadedAt;
    }
}
