// Generated by delombok at Mon Mar 30 15:24:38 IST 2026
package com.collabrium.model;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "milestones")
public class Milestone {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;
    @Column(nullable = false)
    private String title;
    private LocalDate dueDate;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MilestoneStatus status;
    @Column(nullable = false)
    private Integer progressPercentage;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (status == null) status = MilestoneStatus.PENDING;
        if (progressPercentage == null) progressPercentage = 0;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    public static class MilestoneBuilder {

        private Long id;

        private Project project;

        private String title;

        private LocalDate dueDate;

        private MilestoneStatus status;

        private Integer progressPercentage;

        private LocalDateTime createdAt;

        private LocalDateTime updatedAt;

        MilestoneBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public Milestone.MilestoneBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Milestone.MilestoneBuilder project(final Project project) {
            this.project = project;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Milestone.MilestoneBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Milestone.MilestoneBuilder dueDate(final LocalDate dueDate) {
            this.dueDate = dueDate;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Milestone.MilestoneBuilder status(final MilestoneStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Milestone.MilestoneBuilder progressPercentage(final Integer progressPercentage) {
            this.progressPercentage = progressPercentage;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Milestone.MilestoneBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Milestone.MilestoneBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public Milestone build() {
            return new Milestone(this.id, this.project, this.title, this.dueDate, this.status, this.progressPercentage, this.createdAt, this.updatedAt);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "Milestone.MilestoneBuilder(id=" + this.id + ", project=" + this.project + ", title=" + this.title + ", dueDate=" + this.dueDate + ", status=" + this.status + ", progressPercentage=" + this.progressPercentage + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    public static Milestone.MilestoneBuilder builder() {
        return new Milestone.MilestoneBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public Project getProject() {
        return this.project;
    }

    public String getTitle() {
        return this.title;
    }

    public LocalDate getDueDate() {
        return this.dueDate;
    }

    public MilestoneStatus getStatus() {
        return this.status;
    }

    public Integer getProgressPercentage() {
        return this.progressPercentage;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setProject(final Project project) {
        this.project = project;
    }

    public void setTitle(final String title) {
        this.title = title;
    }

    public void setDueDate(final LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public void setStatus(final MilestoneStatus status) {
        this.status = status;
    }

    public void setProgressPercentage(final Integer progressPercentage) {
        this.progressPercentage = progressPercentage;
    }

    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Milestone)) return false;
        final Milestone other = (Milestone) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$progressPercentage = this.getProgressPercentage();
        final java.lang.Object other$progressPercentage = other.getProgressPercentage();
        if (this$progressPercentage == null ? other$progressPercentage != null : !this$progressPercentage.equals(other$progressPercentage)) return false;
        final java.lang.Object this$project = this.getProject();
        final java.lang.Object other$project = other.getProject();
        if (this$project == null ? other$project != null : !this$project.equals(other$project)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$dueDate = this.getDueDate();
        final java.lang.Object other$dueDate = other.getDueDate();
        if (this$dueDate == null ? other$dueDate != null : !this$dueDate.equals(other$dueDate)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Milestone;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $progressPercentage = this.getProgressPercentage();
        result = result * PRIME + ($progressPercentage == null ? 43 : $progressPercentage.hashCode());
        final java.lang.Object $project = this.getProject();
        result = result * PRIME + ($project == null ? 43 : $project.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $dueDate = this.getDueDate();
        result = result * PRIME + ($dueDate == null ? 43 : $dueDate.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "Milestone(id=" + this.getId() + ", project=" + this.getProject() + ", title=" + this.getTitle() + ", dueDate=" + this.getDueDate() + ", status=" + this.getStatus() + ", progressPercentage=" + this.getProgressPercentage() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    public Milestone() {
    }

    public Milestone(final Long id, final Project project, final String title, final LocalDate dueDate, final MilestoneStatus status, final Integer progressPercentage, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.project = project;
        this.title = title;
        this.dueDate = dueDate;
        this.status = status;
        this.progressPercentage = progressPercentage;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
