// Generated by delombok at Mon Mar 30 15:24:38 IST 2026
package com.collabrium.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "projects")
public class Project {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String title;
    @Column(columnDefinition = "TEXT")
    private String description;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ProjectStatus status;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false)
    private User createdBy;
    @OneToMany(mappedBy = "project", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Milestone> milestones;
    @OneToMany(mappedBy = "project", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<ProjectMember> members;
    @OneToMany(mappedBy = "project", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Document> documents;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (status == null) status = ProjectStatus.ACTIVE;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    private static List<Milestone> $default$milestones() {
        return new ArrayList<>();
    }

    private static List<ProjectMember> $default$members() {
        return new ArrayList<>();
    }

    private static List<Document> $default$documents() {
        return new ArrayList<>();
    }

    public static class ProjectBuilder {

        private Long id;

        private String title;

        private String description;

        private ProjectStatus status;

        private User createdBy;

        private boolean milestones$set;

        private List<Milestone> milestones$value;

        private boolean members$set;

        private List<ProjectMember> members$value;

        private boolean documents$set;

        private List<Document> documents$value;

        private LocalDateTime createdAt;

        private LocalDateTime updatedAt;

        ProjectBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public Project.ProjectBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Project.ProjectBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Project.ProjectBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Project.ProjectBuilder status(final ProjectStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Project.ProjectBuilder createdBy(final User createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Project.ProjectBuilder milestones(final List<Milestone> milestones) {
            this.milestones$value = milestones;
            milestones$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Project.ProjectBuilder members(final List<ProjectMember> members) {
            this.members$value = members;
            members$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Project.ProjectBuilder documents(final List<Document> documents) {
            this.documents$value = documents;
            documents$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Project.ProjectBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public Project.ProjectBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public Project build() {
            List<Milestone> milestones$value = this.milestones$value;
            if (!this.milestones$set) milestones$value = Project.$default$milestones();
            List<ProjectMember> members$value = this.members$value;
            if (!this.members$set) members$value = Project.$default$members();
            List<Document> documents$value = this.documents$value;
            if (!this.documents$set) documents$value = Project.$default$documents();
            return new Project(this.id, this.title, this.description, this.status, this.createdBy, milestones$value, members$value, documents$value, this.createdAt, this.updatedAt);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "Project.ProjectBuilder(id=" + this.id + ", title=" + this.title + ", description=" + this.description + ", status=" + this.status + ", createdBy=" + this.createdBy + ", milestones$value=" + this.milestones$value + ", members$value=" + this.members$value + ", documents$value=" + this.documents$value + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    public static Project.ProjectBuilder builder() {
        return new Project.ProjectBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public String getTitle() {
        return this.title;
    }

    public String getDescription() {
        return this.description;
    }

    public ProjectStatus getStatus() {
        return this.status;
    }

    public User getCreatedBy() {
        return this.createdBy;
    }

    public List<Milestone> getMilestones() {
        return this.milestones;
    }

    public List<ProjectMember> getMembers() {
        return this.members;
    }

    public List<Document> getDocuments() {
        return this.documents;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setTitle(final String title) {
        this.title = title;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setStatus(final ProjectStatus status) {
        this.status = status;
    }

    public void setCreatedBy(final User createdBy) {
        this.createdBy = createdBy;
    }

    public void setMilestones(final List<Milestone> milestones) {
        this.milestones = milestones;
    }

    public void setMembers(final List<ProjectMember> members) {
        this.members = members;
    }

    public void setDocuments(final List<Document> documents) {
        this.documents = documents;
    }

    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Project)) return false;
        final Project other = (Project) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createdBy = this.getCreatedBy();
        final java.lang.Object other$createdBy = other.getCreatedBy();
        if (this$createdBy == null ? other$createdBy != null : !this$createdBy.equals(other$createdBy)) return false;
        final java.lang.Object this$milestones = this.getMilestones();
        final java.lang.Object other$milestones = other.getMilestones();
        if (this$milestones == null ? other$milestones != null : !this$milestones.equals(other$milestones)) return false;
        final java.lang.Object this$members = this.getMembers();
        final java.lang.Object other$members = other.getMembers();
        if (this$members == null ? other$members != null : !this$members.equals(other$members)) return false;
        final java.lang.Object this$documents = this.getDocuments();
        final java.lang.Object other$documents = other.getDocuments();
        if (this$documents == null ? other$documents != null : !this$documents.equals(other$documents)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Project;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createdBy = this.getCreatedBy();
        result = result * PRIME + ($createdBy == null ? 43 : $createdBy.hashCode());
        final java.lang.Object $milestones = this.getMilestones();
        result = result * PRIME + ($milestones == null ? 43 : $milestones.hashCode());
        final java.lang.Object $members = this.getMembers();
        result = result * PRIME + ($members == null ? 43 : $members.hashCode());
        final java.lang.Object $documents = this.getDocuments();
        result = result * PRIME + ($documents == null ? 43 : $documents.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "Project(id=" + this.getId() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", status=" + this.getStatus() + ", createdBy=" + this.getCreatedBy() + ", milestones=" + this.getMilestones() + ", members=" + this.getMembers() + ", documents=" + this.getDocuments() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    public Project() {
        this.milestones = Project.$default$milestones();
        this.members = Project.$default$members();
        this.documents = Project.$default$documents();
    }

    public Project(final Long id, final String title, final String description, final ProjectStatus status, final User createdBy, final List<Milestone> milestones, final List<ProjectMember> members, final List<Document> documents, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.status = status;
        this.createdBy = createdBy;
        this.milestones = milestones;
        this.members = members;
        this.documents = documents;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
