// Generated by delombok at Mon Mar 30 15:24:38 IST 2026
package com.collabrium.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "project_members", uniqueConstraints = @UniqueConstraint(name = "uk_project_user", columnNames = {"project_id", "user_id"}))
public class ProjectMember {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(nullable = false, updatable = false)
    private LocalDateTime joinedAt;

    @PrePersist
    protected void onCreate() {
        joinedAt = LocalDateTime.now();
    }

    public static class ProjectMemberBuilder {

        private Long id;

        private Project project;

        private User user;

        private LocalDateTime joinedAt;

        ProjectMemberBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public ProjectMember.ProjectMemberBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ProjectMember.ProjectMemberBuilder project(final Project project) {
            this.project = project;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ProjectMember.ProjectMemberBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public ProjectMember.ProjectMemberBuilder joinedAt(final LocalDateTime joinedAt) {
            this.joinedAt = joinedAt;
            return this;
        }

        public ProjectMember build() {
            return new ProjectMember(this.id, this.project, this.user, this.joinedAt);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "ProjectMember.ProjectMemberBuilder(id=" + this.id + ", project=" + this.project + ", user=" + this.user + ", joinedAt=" + this.joinedAt + ")";
        }
    }

    public static ProjectMember.ProjectMemberBuilder builder() {
        return new ProjectMember.ProjectMemberBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public Project getProject() {
        return this.project;
    }

    public User getUser() {
        return this.user;
    }

    public LocalDateTime getJoinedAt() {
        return this.joinedAt;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setProject(final Project project) {
        this.project = project;
    }

    public void setUser(final User user) {
        this.user = user;
    }

    public void setJoinedAt(final LocalDateTime joinedAt) {
        this.joinedAt = joinedAt;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ProjectMember)) return false;
        final ProjectMember other = (ProjectMember) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$project = this.getProject();
        final java.lang.Object other$project = other.getProject();
        if (this$project == null ? other$project != null : !this$project.equals(other$project)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$joinedAt = this.getJoinedAt();
        final java.lang.Object other$joinedAt = other.getJoinedAt();
        if (this$joinedAt == null ? other$joinedAt != null : !this$joinedAt.equals(other$joinedAt)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ProjectMember;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $project = this.getProject();
        result = result * PRIME + ($project == null ? 43 : $project.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $joinedAt = this.getJoinedAt();
        result = result * PRIME + ($joinedAt == null ? 43 : $joinedAt.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "ProjectMember(id=" + this.getId() + ", project=" + this.getProject() + ", user=" + this.getUser() + ", joinedAt=" + this.getJoinedAt() + ")";
    }

    public ProjectMember() {
    }

    public ProjectMember(final Long id, final Project project, final User user, final LocalDateTime joinedAt) {
        this.id = id;
        this.project = project;
        this.user = user;
        this.joinedAt = joinedAt;
    }
}
