// Generated by delombok at Mon Mar 30 15:24:38 IST 2026
package com.collabrium.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "users", indexes = @Index(name = "idx_user_email", columnList = "email"))
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String name;
    @Column(nullable = false, unique = true)
    private String email;
    @Column(nullable = false)
    private String password;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    @Column(nullable = false)
    private LocalDateTime updatedAt;
    @OneToOne(mappedBy = "user", cascade = CascadeType.REMOVE, orphanRemoval = true)
    private RefreshToken refreshToken;
    @OneToMany(mappedBy = "user", cascade = CascadeType.REMOVE, orphanRemoval = true)
    private List<ProjectMember> projectMembers;
    @OneToMany(mappedBy = "uploadedBy", cascade = CascadeType.REMOVE)
    private List<Document> documents;
    @OneToMany(mappedBy = "createdBy", cascade = CascadeType.REMOVE)
    private List<Project> projects;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    public static class UserBuilder {

        private Long id;

        private String name;

        private String email;

        private String password;

        private Role role;

        private LocalDateTime createdAt;

        private LocalDateTime updatedAt;

        private RefreshToken refreshToken;

        private List<ProjectMember> projectMembers;

        private List<Document> documents;

        private List<Project> projects;

        UserBuilder() {
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder password(final String password) {
            this.password = password;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder role(final Role role) {
            this.role = role;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder refreshToken(final RefreshToken refreshToken) {
            this.refreshToken = refreshToken;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder projectMembers(final List<ProjectMember> projectMembers) {
            this.projectMembers = projectMembers;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder documents(final List<Document> documents) {
            this.documents = documents;
            return this;
        }

        /**
         * @return {@code this}.
         */

        public User.UserBuilder projects(final List<Project> projects) {
            this.projects = projects;
            return this;
        }

        public User build() {
            return new User(this.id, this.name, this.email, this.password, this.role, this.createdAt, this.updatedAt, this.refreshToken, this.projectMembers, this.documents, this.projects);
        }

        @java.lang.Override

        public java.lang.String toString() {
            return "User.UserBuilder(id=" + this.id + ", name=" + this.name + ", email=" + this.email + ", password=" + this.password + ", role=" + this.role + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ", refreshToken=" + this.refreshToken + ", projectMembers=" + this.projectMembers + ", documents=" + this.documents + ", projects=" + this.projects + ")";
        }
    }

    public static User.UserBuilder builder() {
        return new User.UserBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public String getEmail() {
        return this.email;
    }

    public String getPassword() {
        return this.password;
    }

    public Role getRole() {
        return this.role;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public RefreshToken getRefreshToken() {
        return this.refreshToken;
    }

    public List<ProjectMember> getProjectMembers() {
        return this.projectMembers;
    }

    public List<Document> getDocuments() {
        return this.documents;
    }

    public List<Project> getProjects() {
        return this.projects;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setEmail(final String email) {
        this.email = email;
    }

    public void setPassword(final String password) {
        this.password = password;
    }

    public void setRole(final Role role) {
        this.role = role;
    }

    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public void setRefreshToken(final RefreshToken refreshToken) {
        this.refreshToken = refreshToken;
    }

    public void setProjectMembers(final List<ProjectMember> projectMembers) {
        this.projectMembers = projectMembers;
    }

    public void setDocuments(final List<Document> documents) {
        this.documents = documents;
    }

    public void setProjects(final List<Project> projects) {
        this.projects = projects;
    }

    @java.lang.Override

    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof User)) return false;
        final User other = (User) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        final java.lang.Object this$refreshToken = this.getRefreshToken();
        final java.lang.Object other$refreshToken = other.getRefreshToken();
        if (this$refreshToken == null ? other$refreshToken != null : !this$refreshToken.equals(other$refreshToken)) return false;
        final java.lang.Object this$projectMembers = this.getProjectMembers();
        final java.lang.Object other$projectMembers = other.getProjectMembers();
        if (this$projectMembers == null ? other$projectMembers != null : !this$projectMembers.equals(other$projectMembers)) return false;
        final java.lang.Object this$documents = this.getDocuments();
        final java.lang.Object other$documents = other.getDocuments();
        if (this$documents == null ? other$documents != null : !this$documents.equals(other$documents)) return false;
        final java.lang.Object this$projects = this.getProjects();
        final java.lang.Object other$projects = other.getProjects();
        if (this$projects == null ? other$projects != null : !this$projects.equals(other$projects)) return false;
        return true;
    }

    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof User;
    }

    @java.lang.Override

    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        final java.lang.Object $refreshToken = this.getRefreshToken();
        result = result * PRIME + ($refreshToken == null ? 43 : $refreshToken.hashCode());
        final java.lang.Object $projectMembers = this.getProjectMembers();
        result = result * PRIME + ($projectMembers == null ? 43 : $projectMembers.hashCode());
        final java.lang.Object $documents = this.getDocuments();
        result = result * PRIME + ($documents == null ? 43 : $documents.hashCode());
        final java.lang.Object $projects = this.getProjects();
        result = result * PRIME + ($projects == null ? 43 : $projects.hashCode());
        return result;
    }

    @java.lang.Override

    public java.lang.String toString() {
        return "User(id=" + this.getId() + ", name=" + this.getName() + ", email=" + this.getEmail() + ", password=" + this.getPassword() + ", role=" + this.getRole() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ", refreshToken=" + this.getRefreshToken() + ", projectMembers=" + this.getProjectMembers() + ", documents=" + this.getDocuments() + ", projects=" + this.getProjects() + ")";
    }

    public User() {
    }

    public User(final Long id, final String name, final String email, final String password, final Role role, final LocalDateTime createdAt, final LocalDateTime updatedAt, final RefreshToken refreshToken, final List<ProjectMember> projectMembers, final List<Document> documents, final List<Project> projects) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.refreshToken = refreshToken;
        this.projectMembers = projectMembers;
        this.documents = documents;
        this.projects = projects;
    }
}
